apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-backend-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-backend-user
  template:
    metadata:
      labels:
        app: k8s-backend-user
    spec:
      containers:
      - name: k8s-backend-user
        image: bokjunsoo/k8s-backend-user:0.0.4
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        ports:
        - containerPort: 8080