apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-api-gateway
  template:
    metadata:
      labels:
        app: k8s-api-gateway
    spec:
      containers:
      - name: k8s-api-gateway
        image: bokjunsoo/k8s-api-gateway:0.0.1
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE # application.yaml -> application-dev.yml read?
          value: dev
        ports:
        - containerPort: 8080